---
upload_path: "/static/img/:year:/:month:"
frontmatter_file_url_template: "/img/:year:/:month:"
body_file_url_template: "/img/:year:/:month:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
version: '0.26'
