---
hide_body: false
fields:
- name: banner
  label: Banner
  type: text
  hidden: false
  default: ''
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: keywords
  label: Keywords
  type: list
  hidden: false
  default: []
- name: author
  label: Author
  type: text
  hidden: false
  default: ''
- name: images
  label: Images
  type: list
  hidden: false
  default: []
- name: lightbox
  label: Lightbox
  type: boolean
  hidden: false
  default: false
- name: totop
  label: Totop
  type: boolean
  hidden: false
  default: true
